import { Category, MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'm1',
    name: '小小丁',
    description: '經典川菜，嫩滑雞丁配上香脆花生與乾辣椒，香辣開胃。',
    price: 90,
    category: Category.MAINS,
    imageId: 10,
    spiciness: 2,
  },
  {
    id: 'm2',
    name: '揚州炒飯',
    description: '粒粒分明的米飯，加入叉燒、蝦仁、雞蛋與蔥花大火快炒。',
    price: 150,
    category: Category.MAINS,
    imageId: 22,
    spiciness: 0,
  },
  {
    id: 'm3',
    name: '麻婆豆腐',
    description: '嫩豆腐佐以特製豆瓣醬與花椒，麻辣鮮香，下飯首選。',
    price: 140,
    category: Category.MAINS,
    imageId: 33,
    spiciness: 3,
    isVegetarian: true,
  },
  {
    id: 'd1',
    name: '水晶蝦餃',
    description: '皮薄餡大，整隻鮮蝦入餡，口感彈牙鮮美。',
    price: 120,
    category: Category.DIM_SUM,
    imageId: 44,
    spiciness: 0,
  },
  {
    id: 'd2',
    name: '蟹黃燒賣',
    description: '精選豬肉餡，頂端點綴蟹黃，鮮味十足。',
    price: 110,
    category: Category.DIM_SUM,
    imageId: 55,
    spiciness: 0,
  },
  {
    id: 'd3',
    name: '爆漿流沙包',
    description: '鬆軟包子皮包裹著濃郁鹹蛋黃流沙餡，甜鹹適中。',
    price: 90,
    category: Category.DIM_SUM,
    imageId: 66,
    spiciness: 0,
    isVegetarian: true,
  },
  {
    id: 's1',
    name: '酸辣湯',
    description: '木耳、豆腐、竹筍與蛋花，酸辣濃郁，暖胃聖品。',
    price: 80,
    category: Category.SOUPS,
    imageId: 77,
    spiciness: 1,
  },
  {
    id: 's2',
    name: '玉米雞蓉湯',
    description: '鮮甜玉米與滑嫩雞蓉，口感順滑，老少咸宜。',
    price: 80,
    category: Category.SOUPS,
    imageId: 88,
    spiciness: 0,
  },
  {
    id: 'b1',
    name: '港式凍檸茶',
    description: '濃郁錫蘭紅茶加入新鮮黃檸檬，消暑解膩。',
    price: 60,
    category: Category.DRINKS,
    imageId: 99,
    spiciness: 0,
  },
  {
    id: 'b2',
    name: '絲襪奶茶',
    description: '口感絲滑濃厚，茶香奶香完美融合。',
    price: 65,
    category: Category.DRINKS,
    imageId: 102,
    spiciness: 0,
  },
  {
    id: 'r1',
    name: '主廚特製紅燒肉',
    description: '精選五花肉慢火燉煮，肥而不膩，入口即化。',
    price: 220,
    category: Category.RECOMMENDED,
    imageId: 111,
    spiciness: 0,
  }
];

export const CATEGORIES = Object.values(Category);